# Convolutional reccurent network for word recognition

In [1]:
import utils
from audio_processing import AudioProcessor
from convRNN import ConvRNN, Conv2dNN, MultiConvRNN
import tensorflow as tf
import numpy as np
from time import time
from matplotlib import pyplot as plt
% matplotlib inline

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 1 - Define model settings

In [2]:
model_settings = utils.get_default_model_settings()
data_dir = model_settings['data_dir']
wanted_words = model_settings['wanted_words']
validation_percentage = model_settings['validation_percentage']
testing_percentage = model_settings['testing_percentage']
model_settings['strip_window_size_ms'] = 30.0
model_settings['strip_window_stride_ms'] = 10.0
model_settings['window_size_ms'] = 30.0
model_settings['window_stride_ms'] = 10.0

In [ ]:
with tf.Session() as sess:


    proc = AudioProcessor(model_settings,
                                  data_dir,
                                  wanted_words=wanted_words.split(','),
                                  validation_percentage=validation_percentage,
                                  testing_percentage=testing_percentage)
    model_settings = proc._model_settings
    
#     data, labels = proc.get_data(2,0,'training')
#     sample = data[0]
#     reshaped = sample.reshape([sample.shape[0] * sample.shape[1], sample.shape[2]])
#     plt.imshow(np.transpose(reshaped), origin='low')
    conv_rnn = MultiConvRNN("multi_conv_rnn_2", model_settings)
    conv_rnn.train(proc)

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:98: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


INFO:tensorflow:Training from step: 1 
INFO:tensorflow:Step #1: rate 0.001000, accuracy 0.0%, cross entropy 4.958745
INFO:tensorflow:Step #2: rate 0.001000, accuracy 6.0%, cross entropy 4.431256
INFO:tensorflow:Step #3: rate 0.001000, accuracy 3.0%, cross entropy 4.245367
INFO:tensorflow:Step #4: rate 0.001000, accuracy 3.0%, cross entropy 4.101827
INFO:tensorflow:Step #5: rate 0.001000, accuracy 7.0%, cross entropy 3.842594
INFO:tensorflow:Step #6: rate 0.001000, accuracy 1.0%, cross entropy 3.981599
INFO:tensorflow:Step #7: rate 0.001000, accuracy 4.0%, cross entropy 3.761331
INFO:tensorflow:Step #8: rate 0.001000, accuracy 6.0%, cross entropy 3.610201
INFO:tensorflow:Step #9: rate 0.001000, accuracy 5.0%, cross entropy 3.458268
INFO:tensorflow:Step #10: rate 0.001000, accuracy 3.0%, cross entropy 3.524277
INFO:tensorflow:Step #11: rate 0.001000, accuracy 2.0%, cross entropy 3.549221
INFO:tensorflow:Step #12: rate 0.001000, accuracy 5.0%, cross entropy 3.555880
INFO:tensorflow:Step #

INFO:tensorflow:Step #104: rate 0.001000, accuracy 10.0%, cross entropy 3.141811
INFO:tensorflow:Step #105: rate 0.001000, accuracy 4.0%, cross entropy 3.172014
INFO:tensorflow:Step #106: rate 0.001000, accuracy 4.0%, cross entropy 3.177335
INFO:tensorflow:Step #107: rate 0.001000, accuracy 10.0%, cross entropy 3.218673
INFO:tensorflow:Step #108: rate 0.001000, accuracy 7.0%, cross entropy 3.110491
INFO:tensorflow:Step #109: rate 0.001000, accuracy 4.0%, cross entropy 3.184994
INFO:tensorflow:Step #110: rate 0.001000, accuracy 3.0%, cross entropy 3.164028
INFO:tensorflow:Step #111: rate 0.001000, accuracy 8.0%, cross entropy 3.136716
INFO:tensorflow:Step #112: rate 0.001000, accuracy 6.0%, cross entropy 3.151284
INFO:tensorflow:Step #113: rate 0.001000, accuracy 8.0%, cross entropy 3.085072
INFO:tensorflow:Step #114: rate 0.001000, accuracy 2.0%, cross entropy 3.168589
INFO:tensorflow:Step #115: rate 0.001000, accuracy 5.0%, cross entropy 3.158083
INFO:tensorflow:Step #116: rate 0.0010

INFO:tensorflow:Step #206: rate 0.001000, accuracy 6.0%, cross entropy 3.104444
INFO:tensorflow:Step #207: rate 0.001000, accuracy 6.0%, cross entropy 3.079831
INFO:tensorflow:Step #208: rate 0.001000, accuracy 6.0%, cross entropy 3.094242
INFO:tensorflow:Step #209: rate 0.001000, accuracy 7.0%, cross entropy 3.033681
INFO:tensorflow:Step #210: rate 0.001000, accuracy 8.0%, cross entropy 3.007044
INFO:tensorflow:Step #211: rate 0.001000, accuracy 9.0%, cross entropy 3.123519
INFO:tensorflow:Step #212: rate 0.001000, accuracy 5.0%, cross entropy 3.122108
INFO:tensorflow:Step #213: rate 0.001000, accuracy 4.0%, cross entropy 3.011813
INFO:tensorflow:Step #214: rate 0.001000, accuracy 11.0%, cross entropy 2.885314
INFO:tensorflow:Step #215: rate 0.001000, accuracy 7.0%, cross entropy 2.961877
INFO:tensorflow:Step #216: rate 0.001000, accuracy 13.0%, cross entropy 3.012452
INFO:tensorflow:Step #217: rate 0.001000, accuracy 8.0%, cross entropy 3.132874
INFO:tensorflow:Step #218: rate 0.0010

INFO:tensorflow:Step #307: rate 0.001000, accuracy 19.0%, cross entropy 2.632790
INFO:tensorflow:Step #308: rate 0.001000, accuracy 25.0%, cross entropy 2.371175
INFO:tensorflow:Step #309: rate 0.001000, accuracy 17.0%, cross entropy 2.464992
INFO:tensorflow:Step #310: rate 0.001000, accuracy 20.0%, cross entropy 2.769701
INFO:tensorflow:Step #311: rate 0.001000, accuracy 20.0%, cross entropy 2.530841
INFO:tensorflow:Step #312: rate 0.001000, accuracy 22.0%, cross entropy 2.743031
INFO:tensorflow:Step #313: rate 0.001000, accuracy 14.0%, cross entropy 2.441811
INFO:tensorflow:Step #314: rate 0.001000, accuracy 13.0%, cross entropy 2.546188
INFO:tensorflow:Step #315: rate 0.001000, accuracy 18.0%, cross entropy 2.793337
INFO:tensorflow:Step #316: rate 0.001000, accuracy 13.0%, cross entropy 2.539289
INFO:tensorflow:Step #317: rate 0.001000, accuracy 18.0%, cross entropy 2.556100
INFO:tensorflow:Step #318: rate 0.001000, accuracy 23.0%, cross entropy 2.478446
INFO:tensorflow:Step #319: r

INFO:tensorflow:Step #404: rate 0.001000, accuracy 28.0%, cross entropy 2.116007
INFO:tensorflow:Step #405: rate 0.001000, accuracy 35.0%, cross entropy 1.828669
INFO:tensorflow:Step #406: rate 0.001000, accuracy 31.0%, cross entropy 2.059850
INFO:tensorflow:Step #407: rate 0.001000, accuracy 34.0%, cross entropy 1.953914
INFO:tensorflow:Step #408: rate 0.001000, accuracy 35.0%, cross entropy 2.085055
INFO:tensorflow:Step #409: rate 0.001000, accuracy 32.0%, cross entropy 1.969800
INFO:tensorflow:Step #410: rate 0.001000, accuracy 37.0%, cross entropy 1.904358
INFO:tensorflow:Step #411: rate 0.001000, accuracy 36.0%, cross entropy 2.107830
INFO:tensorflow:Step #412: rate 0.001000, accuracy 33.0%, cross entropy 1.920030
INFO:tensorflow:Step #413: rate 0.001000, accuracy 38.0%, cross entropy 1.854133
INFO:tensorflow:Step #414: rate 0.001000, accuracy 26.0%, cross entropy 2.349339
INFO:tensorflow:Step #415: rate 0.001000, accuracy 31.0%, cross entropy 2.206828
INFO:tensorflow:Step #416: r

INFO:tensorflow:Step #505: rate 0.001000, accuracy 47.0%, cross entropy 1.790773
INFO:tensorflow:Step #506: rate 0.001000, accuracy 47.0%, cross entropy 1.604296
INFO:tensorflow:Step #507: rate 0.001000, accuracy 42.0%, cross entropy 1.769485
INFO:tensorflow:Step #508: rate 0.001000, accuracy 46.0%, cross entropy 1.548815
INFO:tensorflow:Step #509: rate 0.001000, accuracy 49.0%, cross entropy 1.800921
INFO:tensorflow:Step #510: rate 0.001000, accuracy 52.0%, cross entropy 1.599436
INFO:tensorflow:Step #511: rate 0.001000, accuracy 57.0%, cross entropy 1.602324
INFO:tensorflow:Step #512: rate 0.001000, accuracy 45.0%, cross entropy 1.724903
INFO:tensorflow:Step #513: rate 0.001000, accuracy 52.0%, cross entropy 1.567213
INFO:tensorflow:Step #514: rate 0.001000, accuracy 57.0%, cross entropy 1.484678
INFO:tensorflow:Step #515: rate 0.001000, accuracy 54.0%, cross entropy 1.488049
INFO:tensorflow:Step #516: rate 0.001000, accuracy 50.0%, cross entropy 1.824914
INFO:tensorflow:Step #517: r

INFO:tensorflow:Step #606: rate 0.001000, accuracy 68.0%, cross entropy 1.216309
INFO:tensorflow:Step #607: rate 0.001000, accuracy 42.0%, cross entropy 1.930106
INFO:tensorflow:Step #608: rate 0.001000, accuracy 65.0%, cross entropy 1.082326
INFO:tensorflow:Step #609: rate 0.001000, accuracy 59.0%, cross entropy 1.374655
INFO:tensorflow:Step #610: rate 0.001000, accuracy 61.0%, cross entropy 1.198982
INFO:tensorflow:Step #611: rate 0.001000, accuracy 75.0%, cross entropy 0.950696
INFO:tensorflow:Step #612: rate 0.001000, accuracy 67.0%, cross entropy 1.221127
INFO:tensorflow:Step #613: rate 0.001000, accuracy 51.0%, cross entropy 1.394749
INFO:tensorflow:Step #614: rate 0.001000, accuracy 62.0%, cross entropy 1.206901
INFO:tensorflow:Step #615: rate 0.001000, accuracy 62.0%, cross entropy 1.221553
INFO:tensorflow:Step #616: rate 0.001000, accuracy 57.0%, cross entropy 1.291054
INFO:tensorflow:Step #617: rate 0.001000, accuracy 58.0%, cross entropy 1.237326
INFO:tensorflow:Step #618: r

INFO:tensorflow:Step #707: rate 0.001000, accuracy 69.0%, cross entropy 0.924763
INFO:tensorflow:Step #708: rate 0.001000, accuracy 75.0%, cross entropy 0.852620
INFO:tensorflow:Step #709: rate 0.001000, accuracy 72.0%, cross entropy 1.009742
INFO:tensorflow:Step #710: rate 0.001000, accuracy 66.0%, cross entropy 1.349381
INFO:tensorflow:Step #711: rate 0.001000, accuracy 69.0%, cross entropy 1.129558
INFO:tensorflow:Step #712: rate 0.001000, accuracy 63.0%, cross entropy 1.206010
INFO:tensorflow:Step #713: rate 0.001000, accuracy 69.0%, cross entropy 1.091399
INFO:tensorflow:Step #714: rate 0.001000, accuracy 70.0%, cross entropy 0.954950
INFO:tensorflow:Step #715: rate 0.001000, accuracy 63.0%, cross entropy 1.143477
INFO:tensorflow:Step #716: rate 0.001000, accuracy 64.0%, cross entropy 1.200367
INFO:tensorflow:Step #717: rate 0.001000, accuracy 68.0%, cross entropy 0.990886
INFO:tensorflow:Step #718: rate 0.001000, accuracy 72.0%, cross entropy 0.873454
INFO:tensorflow:Step #719: r

INFO:tensorflow:Step #804: rate 0.001000, accuracy 71.0%, cross entropy 0.987777
INFO:tensorflow:Step #805: rate 0.001000, accuracy 71.0%, cross entropy 0.946490
INFO:tensorflow:Step #806: rate 0.001000, accuracy 71.0%, cross entropy 0.891689
INFO:tensorflow:Step #807: rate 0.001000, accuracy 75.0%, cross entropy 0.911851
INFO:tensorflow:Step #808: rate 0.001000, accuracy 73.0%, cross entropy 1.034567
INFO:tensorflow:Step #809: rate 0.001000, accuracy 83.0%, cross entropy 0.759665
INFO:tensorflow:Step #810: rate 0.001000, accuracy 71.0%, cross entropy 1.099850
INFO:tensorflow:Step #811: rate 0.001000, accuracy 76.0%, cross entropy 0.981424
INFO:tensorflow:Step #812: rate 0.001000, accuracy 69.0%, cross entropy 0.893648
INFO:tensorflow:Step #813: rate 0.001000, accuracy 73.0%, cross entropy 1.030681
INFO:tensorflow:Step #814: rate 0.001000, accuracy 80.0%, cross entropy 0.795789
INFO:tensorflow:Step #815: rate 0.001000, accuracy 83.0%, cross entropy 0.617330
INFO:tensorflow:Step #816: r

INFO:tensorflow:Step #905: rate 0.001000, accuracy 76.0%, cross entropy 0.765705
INFO:tensorflow:Step #906: rate 0.001000, accuracy 81.0%, cross entropy 0.787941
INFO:tensorflow:Step #907: rate 0.001000, accuracy 78.0%, cross entropy 0.694708
INFO:tensorflow:Step #908: rate 0.001000, accuracy 77.0%, cross entropy 0.818338
INFO:tensorflow:Step #909: rate 0.001000, accuracy 75.0%, cross entropy 0.973698
INFO:tensorflow:Step #910: rate 0.001000, accuracy 75.0%, cross entropy 0.844788
INFO:tensorflow:Step #911: rate 0.001000, accuracy 78.0%, cross entropy 0.853083
INFO:tensorflow:Step #912: rate 0.001000, accuracy 80.0%, cross entropy 0.583858
INFO:tensorflow:Step #913: rate 0.001000, accuracy 66.0%, cross entropy 1.160210
INFO:tensorflow:Step #914: rate 0.001000, accuracy 78.0%, cross entropy 0.898311
INFO:tensorflow:Step #915: rate 0.001000, accuracy 79.0%, cross entropy 0.650785
INFO:tensorflow:Step #916: rate 0.001000, accuracy 80.0%, cross entropy 0.738421
INFO:tensorflow:Step #917: r

INFO:tensorflow:Step #1006: rate 0.001000, accuracy 79.0%, cross entropy 0.848867
INFO:tensorflow:Step #1007: rate 0.001000, accuracy 73.0%, cross entropy 0.859251
INFO:tensorflow:Step #1008: rate 0.001000, accuracy 77.0%, cross entropy 0.657999
INFO:tensorflow:Step #1009: rate 0.001000, accuracy 79.0%, cross entropy 0.681309
INFO:tensorflow:Step #1010: rate 0.001000, accuracy 74.0%, cross entropy 0.831717
INFO:tensorflow:Step #1011: rate 0.001000, accuracy 79.0%, cross entropy 0.820475
INFO:tensorflow:Step #1012: rate 0.001000, accuracy 83.0%, cross entropy 0.634002
INFO:tensorflow:Step #1013: rate 0.001000, accuracy 77.0%, cross entropy 0.784855
INFO:tensorflow:Step #1014: rate 0.001000, accuracy 78.0%, cross entropy 0.683747
INFO:tensorflow:Step #1015: rate 0.001000, accuracy 85.0%, cross entropy 0.481272
INFO:tensorflow:Step #1016: rate 0.001000, accuracy 86.0%, cross entropy 0.452701
INFO:tensorflow:Step #1017: rate 0.001000, accuracy 84.0%, cross entropy 0.751007
INFO:tensorflow:

INFO:tensorflow:Step #1105: rate 0.001000, accuracy 91.0%, cross entropy 0.417563
INFO:tensorflow:Step #1106: rate 0.001000, accuracy 80.0%, cross entropy 0.530530
INFO:tensorflow:Step #1107: rate 0.001000, accuracy 78.0%, cross entropy 0.694492
INFO:tensorflow:Step #1108: rate 0.001000, accuracy 79.0%, cross entropy 0.605586
INFO:tensorflow:Step #1109: rate 0.001000, accuracy 82.0%, cross entropy 0.527202
INFO:tensorflow:Step #1110: rate 0.001000, accuracy 82.0%, cross entropy 0.605593
INFO:tensorflow:Step #1111: rate 0.001000, accuracy 83.0%, cross entropy 0.586667
INFO:tensorflow:Step #1112: rate 0.001000, accuracy 83.0%, cross entropy 0.601231
INFO:tensorflow:Step #1113: rate 0.001000, accuracy 83.0%, cross entropy 0.640147
INFO:tensorflow:Step #1114: rate 0.001000, accuracy 81.0%, cross entropy 0.684861
INFO:tensorflow:Step #1115: rate 0.001000, accuracy 76.0%, cross entropy 0.557948
INFO:tensorflow:Step #1116: rate 0.001000, accuracy 80.0%, cross entropy 0.743678
INFO:tensorflow:

INFO:tensorflow:Step #1201: rate 0.001000, accuracy 85.0%, cross entropy 0.466118
INFO:tensorflow:Step #1202: rate 0.001000, accuracy 87.0%, cross entropy 0.467398
INFO:tensorflow:Step #1203: rate 0.001000, accuracy 89.0%, cross entropy 0.391374
INFO:tensorflow:Step #1204: rate 0.001000, accuracy 79.0%, cross entropy 0.730839
INFO:tensorflow:Step #1205: rate 0.001000, accuracy 82.0%, cross entropy 0.501600
INFO:tensorflow:Step #1206: rate 0.001000, accuracy 89.0%, cross entropy 0.413654
INFO:tensorflow:Step #1207: rate 0.001000, accuracy 86.0%, cross entropy 0.450191
INFO:tensorflow:Step #1208: rate 0.001000, accuracy 84.0%, cross entropy 0.611711
INFO:tensorflow:Step #1209: rate 0.001000, accuracy 82.0%, cross entropy 0.600967
INFO:tensorflow:Step #1210: rate 0.001000, accuracy 83.0%, cross entropy 0.549393
INFO:tensorflow:Step #1211: rate 0.001000, accuracy 89.0%, cross entropy 0.440246
INFO:tensorflow:Step #1212: rate 0.001000, accuracy 85.0%, cross entropy 0.410019
INFO:tensorflow:

INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1300"
INFO:tensorflow:Step #1301: rate 0.001000, accuracy 81.0%, cross entropy 0.651145
INFO:tensorflow:Step #1302: rate 0.001000, accuracy 87.0%, cross entropy 0.518199
INFO:tensorflow:Step #1303: rate 0.001000, accuracy 80.0%, cross entropy 0.681167
INFO:tensorflow:Step #1304: rate 0.001000, accuracy 80.0%, cross entropy 0.684186
INFO:tensorflow:Step #1305: rate 0.001000, accuracy 88.0%, cross entropy 0.572194
INFO:tensorflow:Step #1306: rate 0.001000, accuracy 87.0%, cross entropy 0.429488
INFO:tensorflow:Step #1307: rate 0.001000, accuracy 88.0%, cross entropy 0.516512
INFO:tensorflow:Step #1308: rate 0.001000, accuracy 84.0%, cross entropy 0.499341
INFO:tensorflow:Step #1309: rate 0.001000, accuracy 89.0%, cross entropy 0.485528
INFO:tensorflow:Step #1310: rate 0.001000, accuracy 96.0%, cross entropy 0.203692
INFO:tensorflow:Step #1311: rate 0.001000, accuracy 81.0%, cross entropy 0.649551
INFO:tensorflow:

INFO:tensorflow:Step #1400: rate 0.001000, accuracy 86.0%, cross entropy 0.414507
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1400"
INFO:tensorflow:Step #1401: rate 0.001000, accuracy 86.0%, cross entropy 0.434805
INFO:tensorflow:Step #1402: rate 0.001000, accuracy 85.0%, cross entropy 0.551573
INFO:tensorflow:Step #1403: rate 0.001000, accuracy 84.0%, cross entropy 0.460073
INFO:tensorflow:Step #1404: rate 0.001000, accuracy 90.0%, cross entropy 0.359298
INFO:tensorflow:Step #1405: rate 0.001000, accuracy 90.0%, cross entropy 0.448935
INFO:tensorflow:Step #1406: rate 0.001000, accuracy 88.0%, cross entropy 0.460973
INFO:tensorflow:Step #1407: rate 0.001000, accuracy 83.0%, cross entropy 0.472251
INFO:tensorflow:Step #1408: rate 0.001000, accuracy 88.0%, cross entropy 0.564441
INFO:tensorflow:Step #1409: rate 0.001000, accuracy 90.0%, cross entropy 0.315700
INFO:tensorflow:Step #1410: rate 0.001000, accuracy 78.0%, cross entropy 0.630539
INFO:tensorflow:

INFO:tensorflow:Step #1499: rate 0.001000, accuracy 76.0%, cross entropy 0.776083
INFO:tensorflow:Step #1500: rate 0.001000, accuracy 77.0%, cross entropy 0.614483
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1500"
INFO:tensorflow:Step #1501: rate 0.001000, accuracy 91.0%, cross entropy 0.343242
INFO:tensorflow:Step #1502: rate 0.001000, accuracy 91.0%, cross entropy 0.293313
INFO:tensorflow:Step #1503: rate 0.001000, accuracy 83.0%, cross entropy 0.473040
INFO:tensorflow:Step #1504: rate 0.001000, accuracy 91.0%, cross entropy 0.333961
INFO:tensorflow:Step #1505: rate 0.001000, accuracy 88.0%, cross entropy 0.346128
INFO:tensorflow:Step #1506: rate 0.001000, accuracy 81.0%, cross entropy 0.727815
INFO:tensorflow:Step #1507: rate 0.001000, accuracy 82.0%, cross entropy 0.542181
INFO:tensorflow:Step #1508: rate 0.001000, accuracy 89.0%, cross entropy 0.347705
INFO:tensorflow:Step #1509: rate 0.001000, accuracy 94.0%, cross entropy 0.178720
INFO:tensorflow:

INFO:tensorflow:Step #1598: rate 0.001000, accuracy 84.0%, cross entropy 0.590452
INFO:tensorflow:Step #1599: rate 0.001000, accuracy 89.0%, cross entropy 0.348916
INFO:tensorflow:Step #1600: rate 0.001000, accuracy 88.0%, cross entropy 0.388381
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 206 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
INFO:tensorflow:Step 1600: Validation accuracy = 82.4% (N=5284)
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1600"
INFO:tensorflow:Step #1601: rate 0.001000, accuracy 86.0%, cross entropy 0.431031
INFO:tensorflow:Step #1602: rate 0.001000, accuracy 90.0%, cross entropy 0.422303
INFO:tensorflow:Step #1603: rate 0.001000, accuracy 92.0%, cross entropy 0.307595
INFO:tensorflow:Step #1604: rate 0.001000, accuracy 81.0%, cross entropy 0.568419
INFO:tensorflow:Step #1605: rate 0.001000, accuracy 8

INFO:tensorflow:Step #1694: rate 0.001000, accuracy 84.0%, cross entropy 0.332372
INFO:tensorflow:Step #1695: rate 0.001000, accuracy 87.0%, cross entropy 0.402151
INFO:tensorflow:Step #1696: rate 0.001000, accuracy 93.0%, cross entropy 0.321083
INFO:tensorflow:Step #1697: rate 0.001000, accuracy 89.0%, cross entropy 0.323557
INFO:tensorflow:Step #1698: rate 0.001000, accuracy 88.0%, cross entropy 0.432553
INFO:tensorflow:Step #1699: rate 0.001000, accuracy 85.0%, cross entropy 0.480795
INFO:tensorflow:Step #1700: rate 0.001000, accuracy 89.0%, cross entropy 0.366586
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1700"
INFO:tensorflow:Step #1701: rate 0.001000, accuracy 91.0%, cross entropy 0.281956
INFO:tensorflow:Step #1702: rate 0.001000, accuracy 89.0%, cross entropy 0.325405
INFO:tensorflow:Step #1703: rate 0.001000, accuracy 90.0%, cross entropy 0.317226
INFO:tensorflow:Step #1704: rate 0.001000, accuracy 92.0%, cross entropy 0.255237
INFO:tensorflow:

INFO:tensorflow:Step #1793: rate 0.001000, accuracy 87.0%, cross entropy 0.345341
INFO:tensorflow:Step #1794: rate 0.001000, accuracy 86.0%, cross entropy 0.360842
INFO:tensorflow:Step #1795: rate 0.001000, accuracy 92.0%, cross entropy 0.199825
INFO:tensorflow:Step #1796: rate 0.001000, accuracy 89.0%, cross entropy 0.415994
INFO:tensorflow:Step #1797: rate 0.001000, accuracy 92.0%, cross entropy 0.230251
INFO:tensorflow:Step #1798: rate 0.001000, accuracy 91.0%, cross entropy 0.215433
INFO:tensorflow:Step #1799: rate 0.001000, accuracy 90.0%, cross entropy 0.348907
INFO:tensorflow:Step #1800: rate 0.001000, accuracy 90.0%, cross entropy 0.349911
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1800"
INFO:tensorflow:Step #1801: rate 0.001000, accuracy 86.0%, cross entropy 0.409155
INFO:tensorflow:Step #1802: rate 0.001000, accuracy 92.0%, cross entropy 0.310801
INFO:tensorflow:Step #1803: rate 0.001000, accuracy 89.0%, cross entropy 0.315371
INFO:tensorflow:

INFO:tensorflow:Step #1892: rate 0.001000, accuracy 91.0%, cross entropy 0.261172
INFO:tensorflow:Step #1893: rate 0.001000, accuracy 91.0%, cross entropy 0.332810
INFO:tensorflow:Step #1894: rate 0.001000, accuracy 90.0%, cross entropy 0.263796
INFO:tensorflow:Step #1895: rate 0.001000, accuracy 92.0%, cross entropy 0.240888
INFO:tensorflow:Step #1896: rate 0.001000, accuracy 94.0%, cross entropy 0.268821
INFO:tensorflow:Step #1897: rate 0.001000, accuracy 84.0%, cross entropy 0.511492
INFO:tensorflow:Step #1898: rate 0.001000, accuracy 95.0%, cross entropy 0.176486
INFO:tensorflow:Step #1899: rate 0.001000, accuracy 88.0%, cross entropy 0.318410
INFO:tensorflow:Step #1900: rate 0.001000, accuracy 85.0%, cross entropy 0.351315
INFO:tensorflow:Saving to "/tmp/speech_commands_train\multi_conv_rnn_2.ckpt-1900"
INFO:tensorflow:Step #1901: rate 0.001000, accuracy 91.0%, cross entropy 0.247468
INFO:tensorflow:Step #1902: rate 0.001000, accuracy 89.0%, cross entropy 0.340487
INFO:tensorflow:

INFO:tensorflow:Step #1991: rate 0.001000, accuracy 92.0%, cross entropy 0.319016
INFO:tensorflow:Step #1992: rate 0.001000, accuracy 93.0%, cross entropy 0.307561
INFO:tensorflow:Step #1993: rate 0.001000, accuracy 91.0%, cross entropy 0.305563
INFO:tensorflow:Step #1994: rate 0.001000, accuracy 90.0%, cross entropy 0.332589
INFO:tensorflow:Step #1995: rate 0.001000, accuracy 92.0%, cross entropy 0.269256
INFO:tensorflow:Step #1996: rate 0.001000, accuracy 92.0%, cross entropy 0.234339
INFO:tensorflow:Step #1997: rate 0.001000, accuracy 88.0%, cross entropy 0.486772
INFO:tensorflow:Step #1998: rate 0.001000, accuracy 87.0%, cross entropy 0.383450
INFO:tensorflow:Step #1999: rate 0.001000, accuracy 87.0%, cross entropy 0.353235
INFO:tensorflow:Step #2000: rate 0.001000, accuracy 87.0%, cross entropy 0.312792
INFO:tensorflow:Confusion Matrix:
 [[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 232 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ..

INFO:tensorflow:Step #2087: rate 0.001000, accuracy 87.0%, cross entropy 0.466901
INFO:tensorflow:Step #2088: rate 0.001000, accuracy 93.0%, cross entropy 0.233335
INFO:tensorflow:Step #2089: rate 0.001000, accuracy 90.0%, cross entropy 0.329934
INFO:tensorflow:Step #2090: rate 0.001000, accuracy 90.0%, cross entropy 0.269997
INFO:tensorflow:Step #2091: rate 0.001000, accuracy 87.0%, cross entropy 0.375273
INFO:tensorflow:Step #2092: rate 0.001000, accuracy 88.0%, cross entropy 0.330429
INFO:tensorflow:Step #2093: rate 0.001000, accuracy 92.0%, cross entropy 0.268232
INFO:tensorflow:Step #2094: rate 0.001000, accuracy 90.0%, cross entropy 0.231088
INFO:tensorflow:Step #2095: rate 0.001000, accuracy 91.0%, cross entropy 0.238391
INFO:tensorflow:Step #2096: rate 0.001000, accuracy 88.0%, cross entropy 0.457857
INFO:tensorflow:Step #2097: rate 0.001000, accuracy 83.0%, cross entropy 0.474504
INFO:tensorflow:Step #2098: rate 0.001000, accuracy 91.0%, cross entropy 0.279937
INFO:tensorflow:

## 2 - Create audio processor & data generator

In [4]:
sess = tf.InteractiveSession()
np.random.seed(0)
data_dir = model_settings['data_dir']
wanted_words = model_settings['wanted_words']
validation_percentage = model_settings['validation_percentage']
testing_percentage = model_settings['testing_percentage']
model_settings['strip_window_size_ms'] = 30.0
model_settings['strip_window_stride_ms'] = 30.0
model_settings['window_size_ms'] = 30.0
model_settings['window_stride_ms'] = 10.0

proc = AudioProcessor(model_settings,
                              data_dir,
                              wanted_words=wanted_words.split(','),
                              validation_percentage=validation_percentage,
                              testing_percentage=testing_percentage)

model_settings = proc._model_settings

### 2.1 - test audio processor

In [4]:
# np.random.seed(0)
# proc_test = AudioProcessor(model_settings,
#                           data_dir,
#                           wanted_words=wanted_words.split(','),
#                           validation_percentage=validation_percentage,
#                           testing_percentage=testing_percentage)
# data, labels = proc_test.get_data(10, 0, 'training')
# print('data_shape', data.shape)
# print(labels[0])

# strip_array_length = data.shape[1]
# fig, axes = plt.subplots(1, strip_array_length, sharey=True)
# sample_idx = 9
# norm = plt.Normalize(np.min(data[sample_idx, :, 1:]), np.max(data[sample_idx]))
# print(np.min(data[sample_idx, :, 1:]), np.max(data[sample_idx]))
# for i in range(strip_array_length):
#     axes[i].imshow(np.transpose(data[sample_idx, i]), origin='low', interpolation='none', norm=norm)
#     axes[i].set_title(labels[sample_idx])
# plt.show()

## 3 - Create neural network model

In [5]:

conv_rnn = Conv2dNN("conv2d", model_settings)

In [6]:
proc.get_data(10,0,'training')

(array([[[[-5.73239174e+01, -5.10550022e-01,  5.07846236e-01, ...,
            1.43004328e-01,  1.38319075e-01, -2.57602572e-01],
          [-5.68436890e+01, -1.91585958e+00,  1.61762691e+00, ...,
            1.37288764e-01, -1.62271801e-02, -4.50330943e-01],
          [-5.72463570e+01, -8.53145242e-01,  1.58432996e+00, ...,
            5.72946183e-02,  4.94704172e-02, -6.02206439e-02]],
 
         [[-5.67802048e+01, -7.94092119e-01,  3.39195848e-01, ...,
           -4.67880696e-01,  7.43037313e-02, -1.44618630e-01],
          [-5.63432198e+01,  4.05742735e-01,  1.09172583e+00, ...,
            8.56736377e-02, -3.06711525e-01,  5.34524433e-02],
          [-5.70194855e+01, -4.50131744e-01,  1.40636608e-01, ...,
           -2.86766469e-01, -8.35057255e-03, -4.31324728e-03]],
 
         [[-5.81893501e+01, -9.28468227e-01,  9.04656529e-01, ...,
           -2.78713048e-01,  1.16207786e-01, -1.08538233e-01],
          [-5.77350693e+01, -1.10342920e+00,  3.07572961e-01, ...,
           -5.190

## 4 - Train network

In [7]:
conv_rnn.train(proc)

INFO:tensorflow:Training from step: 1 


InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype string
	 [[Node: Placeholder = Placeholder[dtype=DT_STRING, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 605, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-98962931cfcd>", line 16, in <module>
    testing_percentage=testing_percentage)
  File "C:\Study\Speech_command_classification\audio_processing.py", line 113, in __init__
    self._build_processing_graph()
  File "C:\Study\Speech_command_classification\audio_processing.py", line 236, in _build_processing_graph
    self.wav_filename_placeholder_ = tf.placeholder(tf.string, [])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1746, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4026, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype string
	 [[Node: Placeholder = Placeholder[dtype=DT_STRING, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
